remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: SnipFlow ✂〰
description: A workflow for productive engineers
titles_from_headings:
  enabled: true
  strip_title: true
show_downloads: false
