# Creates a GitHub "Deployment" record, which GH uses to populate the UI
name: "Manually trigger deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Deploy to which environment"
        required: true
        default: "staging"

jobs:
  create-manual-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create Manual GH Deployment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
          script: |
            github.rest.repos.createDeployment({
              environment: "${{ github.event.inputs.environment }}",
              auto_merge: false,
              ref: "${{ github.ref }}",
              owner: context.repo.owner,
              repo: context.repo.repo,
              required_contexts: []
            })
